### ISSUE TITLE
question about atrous convolution

### ISSUE THREAD

**Issue by normandra** [OniroAI/Semantic-segmentation-with-MobileNetV3#5]
I took a look at a bunch of segmentation based mv3 repos on github. Most including yours did not implement the atrous convolution on the final convolution block unlike in the paper. Any particular reason for this?

**Comment by voeykovroman** [comment]
Hi @normandra! Actually, this moment is quite vague in the paper, because they write about atrous convolutions, but they are not specific about what is "the last block of MobileNetV3" for segmentation task (because there are at least 5 feature maps with OS=16). According to the figure 10 they don't actually use atrous conv because for the last feature map they keep the same spatial resolution as for the previous one and only after they apply Lite-RASPP module which exploits 1x1 convolutions and average pooling with big kernel and stride parameters. At least, it was my understanding of the proposed architecture and I think most of the repos were mainly based on figure 10, because text of the paper is not really clear about the segmentation task.

**Comment by normandra** [comment]
I see, thanks for the explanation!
